field: a33bef85-1ee8-42a8-9813-b5e5970e49b4 # Lifts
fieldLayouts:
  561ae1e0-15fa-42f9-b6dc-7ce610379bc8:
    tabs:
      -
        elements:
          -
            fieldUid: 739bd0da-7752-4219-b992-504932cac84f # Left Bank
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1225c3a8-e41b-41be-b1bb-63fa42728169 # Right Bank
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6777391e-bc08-4840-9cc4-c1b87ed36a94 # Additional Information
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  739bd0da-7752-4219-b992-504932cac84f: # Left Bank
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: leftBank
    instructions: ''
    name: 'Left Bank'
    searchable: false
    settings:
      default: true
      offLabel: Inactive
      onLabel: Active
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  1225c3a8-e41b-41be-b1bb-63fa42728169: # Right Bank
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: rightBank
    instructions: ''
    name: 'Right Bank'
    searchable: false
    settings:
      default: true
      offLabel: Inactive
      onLabel: Active
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  6777391e-bc08-4840-9cc4-c1b87ed36a94: # Additional Information
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: additionalInformation
    instructions: ''
    name: 'Additional Information'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: information
name: Information
sortOrder: 1
