defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  9626d010-a6cf-412c-9288-e128e7167564: # Bridges London
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
