field: 8fb03fb1-183a-4b68-9573-f7693efba43c # Escalators
fieldLayouts:
  63f7017c-919e-4598-bc12-7da275b362e6:
    tabs:
      -
        elements:
          -
            fieldUid: 1657abdf-70f1-4826-9ff9-ab2668467dbc # Show escalator information
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5e682297-3369-4a6b-9037-db55250e2d10 # Left bank
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 18748439-580f-4779-be1c-3ea413f977e5 # Right bank
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5e682297-3369-4a6b-9037-db55250e2d10: # Left bank
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: leftBank
    instructions: ''
    name: 'Left bank'
    searchable: false
    settings:
      default: true
      offLabel: Inactive
      onLabel: Active
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  1657abdf-70f1-4826-9ff9-ab2668467dbc: # Show escalator information
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showEscalatorInformation
    instructions: ''
    name: 'Show escalator information'
    searchable: false
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  18748439-580f-4779-be1c-3ea413f977e5: # Right bank
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: rightBank
    instructions: ''
    name: 'Right bank'
    searchable: false
    settings:
      default: true
      offLabel: Inactive
      onLabel: Active
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: information
name: Information
sortOrder: 1
