field: e2623858-1474-4e36-84f3-3be77a357922 # Ferries
fieldLayouts:
  aeb2b4cb-fd87-49ca-8e61-b947432d1c27:
    tabs:
      -
        elements:
          -
            fieldUid: 54998b53-b836-41c2-af34-c64eaa7d7f98 # Show ferry information
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 67e08fad-b132-4713-a365-c9f06f79b5f1 # Left bank
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d9f24cec-d58c-4162-9a06-b0eb6d3196bc # Right bank
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  67e08fad-b132-4713-a365-c9f06f79b5f1: # Left bank
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: leftBank
    instructions: ''
    name: 'Left bank'
    searchable: false
    settings:
      default: true
      offLabel: Inactive
      onLabel: Active
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  54998b53-b836-41c2-af34-c64eaa7d7f98: # Show ferry information
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showFerryInformation
    instructions: ''
    name: 'Show ferry information'
    searchable: false
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  d9f24cec-d58c-4162-9a06-b0eb6d3196bc: # Right bank
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: rightBank
    instructions: ''
    name: 'Right bank'
    searchable: false
    settings:
      default: true
      offLabel: Inactive
      onLabel: Active
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: information
name: Information
sortOrder: 1
